<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OrderPdf.Application\OrderPdf.Application.csproj" />
    <ProjectReference Include="..\OrderPdf.Domain\OrderPdf.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IronPdf" Version="2026.9.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
